name: Static analysis & unit tests
on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Unit tests with unittest.sh
      run: make test

    - name: Static analysis with shellcheck
      run: make check

    - name: Print debug info
      run: make debug

  OpenBSD-VM:
    runs-on: macos-12
    name: OpenBSD in VirtualBox on MacOS
    steps:
    - uses: actions/checkout@v3

    - name: Unit tests & static analysis
      uses: vmactions/openbsd-vm@v0
      with:
        prepare: pkg_add git go shellcheck
        run: make