name: Static analysis & unit tests
on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Unit tests with unittest.sh
      run: TERM=vt100 make test

    - name: Static analysis with shellcheck
      run: make check

    - name: Print debug info
      run: make debug

